#!/usr/bin/env python3
"""
Calgary MediSpa AI - Injector Training Tracker
Tracks the 8-stage onboarding checklist for injector staff.
"""

import click
import json
from datetime import datetime
from pathlib import Path


TRAINING_STAGES = [
    {"id": 1, "name": "Orientation",           "description": "Clinic tour, policies, HIPAA/HIA privacy training, team introductions"},
    {"id": 2, "name": "Consent Forms",          "description": "Review all consent forms, patient intake procedures, documentation standards"},
    {"id": 3, "name": "Product Knowledge",      "description": "Botox, fillers, weight loss, skin care — mechanism, dosing, storage, contraindications"},
    {"id": 4, "name": "Injection Anatomy",      "description": "Facial anatomy, danger zones, vascular structures, topographical review"},
    {"id": 5, "name": "Emergency Protocol",     "description": "Anaphylaxis, vascular occlusion, hyaluronidase protocol, 911 procedures"},
    {"id": 6, "name": "Shadowing",              "description": "Minimum 5 supervised observation sessions with senior injector"},
    {"id": 7, "name": "Supervised Treatment",   "description": "Minimum 10 supervised treatments with direct oversight and feedback"},
    {"id": 8, "name": "Final Sign-Off",         "description": "Physician sign-off, competency assessment, independent practice approval"},
]

DATA_FILE = Path("outputs") / "training_data.json"


def load_data():
    """Load existing training data from JSON file."""
    if DATA_FILE.exists():
        with open(DATA_FILE) as f:
            return json.load(f)
    return {}


def save_data(data):
    """Save training data to JSON file."""
    DATA_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(DATA_FILE, "w") as f:
        json.dump(data, f, indent=2)


def get_or_create_injector(data, name):
    """Get or create an injector record."""
    if name not in data:
        data[name] = {
            "name": name,
            "start_date": datetime.now().strftime("%Y-%m-%d"),
            "stages": {str(s["id"]): {"completed": False, "date": None, "notes": ""} for s in TRAINING_STAGES},
        }
    return data[name]


def update_stage(injector_record, stage_id, completed, notes=""):
    """Mark a stage as completed or pending."""
    stage_key = str(stage_id)
    if stage_key in injector_record["stages"]:
        injector_record["stages"][stage_key]["completed"] = completed
        if completed:
            injector_record["stages"][stage_key]["date"] = datetime.now().strftime("%Y-%m-%d")
        if notes:
            injector_record["stages"][stage_key]["notes"] = notes


def generate_report(data):
    """Generate a markdown training status report."""
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "# Injector Training Tracker Report",
        f"**Clinic:** Calgary MediSpa",
        f"**Generated:** {generated_at}",
        f"**Active Injectors:** {len(data)}",
        "", "---", "",
    ]

    if not data:
        lines.append("No injectors registered yet. Run the tracker and add an injector.")
        return "\n".join(lines)

    for name, record in data.items():
        completed = sum(1 for s in record["stages"].values() if s["completed"])
        total = len(TRAINING_STAGES)
        pct = int((completed / total) * 100)
        status = "CERTIFIED" if completed == total else "IN PROGRESS"

        lines.extend([
            f"## {name}",
            f"**Status:** {status} ({pct}% complete)",
            f"**Start Date:** {record.get('start_date', 'Unknown')}",
            f"**Stages Completed:** {completed}/{total}",
            "",
            "| Stage | Name | Status | Date | Notes |",
            "|---|---|---|---|---|",
        ])

        for stage in TRAINING_STAGES:
            s = record["stages"].get(str(stage["id"]), {})
            status_icon = "DONE" if s.get("completed") else "PENDING"
            date_val = s.get("date", "-") or "-"
            notes_val = s.get("notes", "") or ""
            lines.append(f"| {stage['id']} | {stage['name']} | {status_icon} | {date_val} | {notes_val} |")

        lines.append("")
        lines.append(f"**Stage Descriptions:**")
        for stage in TRAINING_STAGES:
            s = record["stages"].get(str(stage["id"]), {})
            check = "x" if s.get("completed") else " "
            lines.append(f"- [{check}] **{stage['name']}**: {stage['description']}")
        lines.extend(["", "---", ""])

    lines.extend([
        "## Legend",
        "- DONE = Stage completed and documented",
        "- PENDING = Not yet completed",
        "- CERTIFIED = All 8 stages complete, physician sign-off obtained",
        "",
        "*Generated by Calgary MediSpa AI Training Tracker*",
    ])
    return "\n".join(lines)


def run(safe_save):
    """Main entry point for training tracker."""
    click.echo("\n  INJECTOR TRAINING TRACKER")
    click.echo("  Track onboarding checklist for injector staff.\n")

    data = load_data()

    click.echo("  What would you like to do?")
    click.echo("  1. View all training status (generate report)")
    click.echo("  2. Add or update an injector's progress")
    click.echo("  3. Add a new injector")

    choice = input("  Enter choice (1-3): ").strip()

    if choice == "1" or choice == "":
        # Generate report only
        pass

    elif choice == "2" or choice == "3":
        name = input("  Enter injector's full name: ").strip()
        if not name:
            click.echo("  ERROR: Name is required.")
            return

        injector = get_or_create_injector(data, name)

        if choice == "2":
            click.echo(f"\n  Updating training for: {name}")
            click.echo("  Enter stage numbers to mark as completed (space-separated),")
            click.echo("  or press Enter to skip updates.")
            click.echo("  Stages: " + ", ".join(f"{s['id']}={s['name']}" for s in TRAINING_STAGES))

            completed_input = input("  Completed stages: ").strip()
            if completed_input:
                for stage_id in completed_input.split():
                    try:
                        stage_id_int = int(stage_id)
                        if 1 <= stage_id_int <= 8:
                            notes = input(f"  Notes for stage {stage_id_int} (optional): ").strip()
                            update_stage(injector, stage_id_int, True, notes)
                            click.echo(f"  Stage {stage_id_int} marked as complete.")
                    except ValueError:
                        click.echo(f"  Invalid stage ID: {stage_id}")

        save_data(data)
        click.echo(f"  Data saved for {name}.")

    report = generate_report(data)
    date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    filepath = Path("outputs") / f"Training_Report_{date_str}.md"
    saved = safe_save(filepath, report)
    if saved:
        click.echo(f"\n  Training report saved: {filepath}")


if __name__ == "__main__":
    def _save(path, content):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"Saved: {path}")
        return True
    run(_save)
