#!/usr/bin/env python3
"""
Calgary MediSpa AI — SOAP Note Generator
Converts raw treatment notes or transcripts into structured,
audit-ready clinical SOAP notes.
"""

import click
from datetime import datetime
from pathlib import Path


SOAP_TEMPLATE = """# SOAP Clinical Note
**Clinic:** Calgary MediSpa
**Date:** {date}
**Time:** {time}
**Encounter Duration:** {duration}
**Provider:** {provider}
**Chaperone Present:** {chaperone}
**Consent Obtained:** {consent}

---

## S — Subjective
*Patient's reported concerns, history, and reason for visit*

{subjective}

---

## O — Objective
*Provider observations, measurements, product used, units administered*

{objective}

---

## A — Assessment
*Clinical assessment, suitability, contraindication review*

{assessment}

---

## P — Plan
*Treatment performed, follow-up instructions, next appointment*

{plan}

---

## Audit Notes
- This note was generated by Calgary MediSpa AI
- Generated: {generated_at}
- All fields must be reviewed and verified by the treating provider before filing
- This note does not constitute a final medical record until signed by a licensed provider
- Retain for minimum 10 years per Alberta Health Information Act requirements

---
*Calgary MediSpa | Physician-Led Aesthetic Medicine | Calgary, AB*
"""


def get_multiline_input(prompt: str) -> str:
    """Collect multi-line terminal input until user types END on its own line."""
    click.echo(f"\n  {prompt}")
    click.echo("  (Type your notes below. Enter 'END' on a new line when done)")
    click.echo("  " + "-" * 40)
    lines = []
    while True:
        try:
            line = input("  ")
            if line.strip().upper() == "END":
                break
            lines.append(line)
        except EOFError:
            break
    return "\n".join(lines) if lines else "[Not provided]"


def run(safe_save):
    """Main entry point for SOAP note generation."""
    click.echo("\n  SOAP NOTE GENERATOR")
    click.echo("  Paste or type raw treatment notes below.")
    click.echo("  The system will structure them into a SOAP format.\n")

    # Collect header information
    date = input("  Treatment date (YYYY-MM-DD) or press Enter for today: ").strip()
    if not date:
        date = datetime.now().strftime("%Y-%m-%d")

    time_val = input("  Treatment time (e.g. 14:30) or press Enter for now: ").strip()
    if not time_val:
        time_val = datetime.now().strftime("%H:%M")

    provider = input("  Provider name/initials: ").strip() or "[Provider]"
    duration = input("  Encounter duration (e.g. 45 minutes): ").strip() or "[Not recorded]"
    chaperone = input("  Chaperone present? (yes/no): ").strip() or "Not recorded"
    consent = input("  Verbal and written consent obtained? (yes/no): ").strip() or "Not recorded"

    # Collect SOAP sections
    click.echo("\n  --- SOAP SECTIONS ---")
    subjective = get_multiline_input("S — SUBJECTIVE: Patient's chief complaint, history, concerns:")
    objective = get_multiline_input("O — OBJECTIVE: Your observations, product used, units, technique:")
    assessment = get_multiline_input("A — ASSESSMENT: Clinical assessment, contraindications reviewed:")
    plan = get_multiline_input("P — PLAN: Treatment performed, aftercare given, follow-up plan:")

    # Build note
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    note = SOAP_TEMPLATE.format(
        date=date,
        time=time_val,
        duration=duration,
        provider=provider,
        chaperone=chaperone,
        consent=consent,
        subjective=subjective,
        objective=objective,
        assessment=assessment,
        plan=plan,
        generated_at=generated_at,
    )

    # Save output
    filename = f"SOAP_{date.replace('-', '')}_{datetime.now().strftime('%H%M%S')}.md"
    filepath = Path("outputs") / filename

    click.echo("\n  --- PREVIEW ---")
    click.echo("  " + "=" * 50)
    # Show a brief preview
    for line in note.split("\n")[:20]:
        click.echo(f"  {line}")
    click.echo("  ... (full note will be saved)")
    click.echo("  " + "=" * 50)

    saved = safe_save(filepath, note)
    if saved:
        click.echo(f"\n  SOAP note saved successfully: {filepath}")
        click.echo("  IMPORTANT: Review and sign this note before filing.")
    else:
        click.echo("\n  SOAP note was not saved.")


if __name__ == "__main__":
    # Allow direct execution for testing
    def _save(path, content):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"Saved: {path}")
        return True
    run(_save)
