#!/usr/bin/env python3
"""
Calgary MediSpa AI - Goal & KPI Tracker
Tracks weekly goals, KPIs, and staff accountability.
"""

import click
from datetime import datetime
from pathlib import Path

KPI_PLACEHOLDERS = [
    ("Monthly Revenue", "$ ___", "Target: $ ___"),
    ("New Patient Consultations", "___ booked", "Target: ___/month"),
    ("Treatment Conversion Rate", "___ %", "Target: 70%+"),
    ("Patient Retention Rate", "___ %", "Target: 80%+"),
    ("Staff Utilization Rate", "___ %", "Target: 85%+"),
    ("Google Review Score", "___ stars", "Target: 4.8+"),
    ("Social Media Engagement", "___ interactions", "Target: ___/week"),
    ("Referral Source Tracking", "Top source: ___", "Diversify channels"),
]


def collect_list(prompt, count=None):
    click.echo(f"  {prompt} (type END when done)")
    items = []
    i = 1
    while True:
        val = input(f"    {i}. ").strip()
        if val.upper() == "END" or val == "":
            break
        items.append(val)
        i += 1
        if count and i > count:
            break
    return items


def generate_tracker(data):
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    week = data.get("week", datetime.now().strftime("Week of %B %d, %Y"))
    lines_out = [
        f"# Goal & KPI Tracker",
        f"**Clinic:** Calgary MediSpa",
        f"**Period:** {week}",
        f"**Generated:** {generated_at}",
        "", "---", "",
        "## Weekly Goals", "",
    ]
    for i, goal in enumerate(data.get("goals", []), 1):
        lines_out.append(f"- [ ] **Goal {i}:** {goal}")
    lines_out.extend(["", "---", "", "## KPI Dashboard", "",
        "| KPI | Current | Target | Notes |",
        "|---|---|---|---|"])
    for kpi_name, current, target in KPI_PLACEHOLDERS:
        entered = data.get("kpis", {}).get(kpi_name, current)
        lines_out.append(f"| {kpi_name} | {entered} | {target} | |")
    lines_out.extend(["", "---", "", "## Staff Accountability", ""])
    for item in data.get("staff_items", []):
        lines_out.append(f"- [ ] {item}")
    lines_out.extend(["", "---", "", "## This Week's Wins", ""])
    for win in data.get("wins", []):
        lines_out.append(f"- {win}")
    lines_out.extend(["", "---", "", "## Challenges / Blockers", ""])
    for challenge in data.get("challenges", []):
        lines_out.append(f"- {challenge}")
    lines_out.extend(["", "---", "", "## Focus for Next Week", ""])
    for focus in data.get("next_week", []):
        lines_out.append(f"- {focus}")
    lines_out.extend([
        "", "---", "",
        "## Notes",
        "",
        data.get("notes", "[No additional notes]"),
        "",
        "*Generated by Calgary MediSpa AI Goal Tracker*"
    ])
    return "\n".join(lines_out)


def run(safe_save):
    click.echo("\n  GOAL & KPI TRACKER")
    click.echo("  Track weekly goals, KPIs, and clinic performance.\n")
    week = input("  Week/Period (or Enter for current week): ").strip()
    if not week:
        week = datetime.now().strftime("Week of %B %d, %Y")
    goals = collect_list("Weekly goals:")
    click.echo("\n  KPI Entry (press Enter to skip any KPI):")
    kpis = {}
    for kpi_name, placeholder, target in KPI_PLACEHOLDERS:
        val = input(f"    {kpi_name} [{target}]: ").strip()
        if val:
            kpis[kpi_name] = val
    staff_items = collect_list("\n  Staff accountability items:")
    wins = collect_list("\n  This week's wins:")
    challenges = collect_list("\n  Challenges or blockers:")
    next_week = collect_list("\n  Focus items for next week:")
    notes = input("\n  Additional notes (or Enter to skip): ").strip()
    data = {"week": week, "goals": goals, "kpis": kpis,
            "staff_items": staff_items, "wins": wins,
            "challenges": challenges, "next_week": next_week, "notes": notes}
    tracker = generate_tracker(data)
    date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    filepath = Path("outputs") / f"Goals_KPI_{date_str}.md"
    saved = safe_save(filepath, tracker)
    if saved:
        click.echo(f"\n  Goal tracker saved: {filepath}")


if __name__ == "__main__":
    def _save(path, content):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"Saved: {path}")
        return True
    run(_save)
