#!/usr/bin/env python3
"""
Calgary MediSpa AI - Meeting Notes Organizer
Structures meeting notes with action items and follow-ups.
"""

import click
from datetime import datetime
from pathlib import Path


def get_multiline(prompt):
    click.echo(f"  {prompt} (type END on new line when done)")
    lines_in = []
    while True:
        try:
            line = input("  ")
            if line.strip().upper() == "END":
                break
            lines_in.append(line)
        except EOFError:
            break
    return "\n".join(lines_in) if lines_in else "[None recorded]"


def collect_list(prompt, hint="Enter each item, then Enter. Type END when done."):
    click.echo(f"  {prompt}")
    click.echo(f"  ({hint})")
    items = []
    while True:
        val = input(f"    - ").strip()
        if val.upper() == "END" or val == "":
            break
        items.append(val)
    return items


def generate_notes(data):
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines_out = [
        f"# Meeting Notes — {data['title']}",
        f"**Clinic:** Calgary MediSpa",
        f"**Date:** {data['date']}",
        f"**Time:** {data['time']}",
        f"**Facilitator:** {data['facilitator']}",
        f"**Attendees:** {data['attendees']}",
        f"**Duration:** {data['duration']}",
        f"**Generated:** {generated_at}",
        "", "---", "", "## Agenda Items", "",
    ]
    for item in data.get("agenda", []):
        lines_out.append(f"- {item}")
    lines_out.extend(["", "---", "", "## Discussion Notes", ""])
    lines_out.append(data.get("notes", "[No notes recorded]"))
    lines_out.extend(["", "---", "", "## Decisions Made", ""])
    for d in data.get("decisions", []):
        lines_out.append(f"- {d}")
    lines_out.extend(["", "---", "", "## Action Items", "",
        "| # | Action | Owner | Due Date | Status |",
        "|---|---|---|---|---|"])
    for i, action in enumerate(data.get("actions", []), 1):
        lines_out.append(f"| {i} | {action['task']} | {action['owner']} | {action['due']} | Pending |")
    lines_out.extend(["", "---", "", "## Next Meeting", "",
        f"**Date:** {data.get('next_meeting', 'TBD')}",
        f"**Agenda Preview:** {data.get('next_agenda', 'TBD')}",
        "", "*Generated by Calgary MediSpa AI Meeting Notes*"])
    return "\n".join(lines_out)


def run(safe_save):
    click.echo("\n  MEETING NOTES ORGANIZER")
    click.echo("  Structure your meeting notes with action items.\n")
    title = input("  Meeting title (e.g. Weekly Team Standup): ").strip() or "Team Meeting"
    date = input("  Date (YYYY-MM-DD) or Enter for today: ").strip() or datetime.now().strftime("%Y-%m-%d")
    time = input("  Time (e.g. 9:00 AM): ").strip() or datetime.now().strftime("%H:%M")
    facilitator = input("  Facilitator name: ").strip() or "[Facilitator]"
    attendees = input("  Attendees (comma-separated): ").strip() or "[All staff]"
    duration = input("  Meeting duration (e.g. 30 minutes): ").strip() or "[Not recorded]"
    agenda = collect_list("Agenda items (type each, Enter after each, END to finish):")
    notes = get_multiline("\n  Discussion notes:")
    decisions = collect_list("\n  Decisions made:")
    click.echo("\n  Action items (enter each action, then owner and due date):")
    actions = []
    while True:
        task = input("    Action item (or END): ").strip()
        if task.upper() == "END" or task == "":
            break
        owner = input("      Owner: ").strip() or "TBD"
        due = input("      Due date: ").strip() or "TBD"
        actions.append({"task": task, "owner": owner, "due": due})
    next_meeting = input("\n  Next meeting date: ").strip() or "TBD"
    next_agenda = input("  Next meeting agenda preview: ").strip() or "TBD"
    data = {"title": title, "date": date, "time": time, "facilitator": facilitator,
            "attendees": attendees, "duration": duration, "agenda": agenda,
            "notes": notes, "decisions": decisions, "actions": actions,
            "next_meeting": next_meeting, "next_agenda": next_agenda}
    meeting_notes = generate_notes(data)
    date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = title.replace(" ", "_").replace("/", "-")[:30]
    filepath = Path("outputs") / f"Meeting_{safe_title}_{date_str}.md"
    saved = safe_save(filepath, meeting_notes)
    if saved:
        click.echo(f"\n  Meeting notes saved: {filepath}")


if __name__ == "__main__":
    def _save(path, content):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
        print(f"Saved: {path}")
        return True
    run(_save)
